### ISSUE TITLE
Calculated values are very different from Pandas_ta or ta_lib

### ISSUE THREAD

**Issue by avinash-br** [RomFR57/fastfinance#3]
**Describe the bug**
ema, supertrend, rsi all calculated values are having a discrepency of upto 0.1% which generates wrong signals.
Is there any difference in your calculation? according to investopedia equations used are correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/59632632/175798908-a9b4c6da-3247-445f-939f-d2f6d1a482f1.png)

**Comment by RomFR57** [comment]
Hello,
I think this is pretty normal because first, I use a "smoothing" parameter for ema. It is set to 2.0 but you can modify it (also in rsi). Maybe you could find the same results by changing it. Second, this ema is a strict one which means that the first values before period are undefined. I think TA-libs compute them which could lead to different results. For supertrend, there are different ways of calculate it, I used one with results closed to TradingView results, not TA-libs. If you have a better algorithm for supertrend, you can send to me, I will update it. Did you ask TA-libs and so why their results are different from fastfinance results ? :smile:
